# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/common_messages.proto',
  package='com.mindtickle.storage.pb.common',
  syntax='proto3',
  serialized_options=b'\n&com.mindtickle.storageprotos.pb.commonB\013CommonProtoZ-github.com/MindTickle/storageprotos/pb/common',
  serialized_pb=b'\n\x1c\x63ommon/common_messages.proto\x12 com.mindtickle.storage.pb.common\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n\x0eRequestContext\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\"\xad\x01\n\x0ePlatformFields\x12/\n\x0b\x63reate_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncreated_by\x18\x03 \x01(\t\x12\x12\n\nupdated_by\x18\x04 \x01(\t\x12\x11\n\ttenant_id\x18\x05 \x01(\tBd\n&com.mindtickle.storageprotos.pb.commonB\x0b\x43ommonProtoZ-github.com/MindTickle/storageprotos/pb/commonb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_REQUESTCONTEXT = _descriptor.Descriptor(
  name='RequestContext',
  full_name='com.mindtickle.storage.pb.common.RequestContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.mindtickle.storage.pb.common.RequestContext.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenant_id', full_name='com.mindtickle.storage.pb.common.RequestContext.tenant_id', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=151,
)


_PLATFORMFIELDS = _descriptor.Descriptor(
  name='PlatformFields',
  full_name='com.mindtickle.storage.pb.common.PlatformFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='create_time', full_name='com.mindtickle.storage.pb.common.PlatformFields.create_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='com.mindtickle.storage.pb.common.PlatformFields.update_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_by', full_name='com.mindtickle.storage.pb.common.PlatformFields.created_by', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_by', full_name='com.mindtickle.storage.pb.common.PlatformFields.updated_by', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenant_id', full_name='com.mindtickle.storage.pb.common.PlatformFields.tenant_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=327,
)

_PLATFORMFIELDS.fields_by_name['create_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PLATFORMFIELDS.fields_by_name['update_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['RequestContext'] = _REQUESTCONTEXT
DESCRIPTOR.message_types_by_name['PlatformFields'] = _PLATFORMFIELDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestContext = _reflection.GeneratedProtocolMessageType('RequestContext', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCONTEXT,
  '__module__' : 'common.common_messages_pb2'
  # @@protoc_insertion_point(class_scope:com.mindtickle.storage.pb.common.RequestContext)
  })
_sym_db.RegisterMessage(RequestContext)

PlatformFields = _reflection.GeneratedProtocolMessageType('PlatformFields', (_message.Message,), {
  'DESCRIPTOR' : _PLATFORMFIELDS,
  '__module__' : 'common.common_messages_pb2'
  # @@protoc_insertion_point(class_scope:com.mindtickle.storage.pb.common.PlatformFields)
  })
_sym_db.RegisterMessage(PlatformFields)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
